  name: myCLI
  
  on: 
    push:
      branches:
        - 'main'
        - 'pokus'
  jobs:
    welcome:
      runs-on: ubuntu-20.04
      
      steps:
        - uses: actions/checkout@v3
        - uses: action/setup-dotnet@v2
          with:
            dotnet-version: '3.1.x'
          
        - name: MSG
          run: echo "..."
          
        - name: Build
          run: dotnet build ActionsKata
          
        - name: Test
          run: dotnet test ActionsKata



